/**
 * Site-wide constants. Most data lives in /data/*.json — this file holds only
 * the values referenced by app/layout.tsx metadata + SEO/structured data.
 *
 * NOTE on `url`: This is the canonical base URL for OG cards, Twitter cards,
 * sitemap.xml, JSON-LD, robots.txt. If/when a custom domain (gyane.sh) is
 * pointed at Vercel, swap this — every downstream piece resolves from here.
 */

export const SITE_CONFIG = {
  name: "Gyanesh Samanta",
  title: "Gyanesh Samanta — Product Manager",
  description:
    "PM with T-shaped skills in Data Storytelling, Consumer Behaviour & AI. Building B2B product experiences. Always shipping.",
  url: "https://gyaneshsamanta.vercel.app",
  // OG image is auto-generated by app/opengraph-image.tsx — Next.js App Router
  // discovers and links it automatically. This constant is kept for any
  // legacy/explicit reference (sitemap.xml uses it).
  ogImage: "https://gyaneshsamanta.vercel.app/opengraph-image",
  twitterHandle: "@GyaneshSamanta",
  links: {
    github: "https://github.com/GyaneshSamanta",
    linkedin: "https://linkedin.com/in/gyanesh-samanta",
    youtube: "https://www.youtube.com/channel/UCWga4RrqehgwPS-MUvT4w4g",
    newsletter:
      "https://www.linkedin.com/newsletters/gyanesh-on-product-6979386586404651008/",
    email: "mail.gyaneshsamanta@gmail.com",
  },
  // Keywords for SEO discoverability when people search "Gyanesh Samanta"
  // or related terms.
  keywords: [
    "Gyanesh Samanta",
    "Gyanesh Samanta Product Manager",
    "Product Manager",
    "Data Storytelling",
    "Consumer Behaviour",
    "AI Product Manager",
    "B2B Product Manager",
    "Outbound PM",
    "XIM Bhubaneswar",
    "Gyanesh on Product",
    "IBM",
    "Ginesys",
    "Snapdeal",
  ],
};
